Pycharm/controllers/client_modif.py
#! /usr/bin/python
# -*- coding:utf-8 -*-
from flask import Blueprint
from flask import Flask, request, render_template, redirect, url_for, abort, flash, session, g

from connexion_db import get_db

client_modif = Blueprint('client_modif', __name__,
                         template_folder='templates')


@client_modif.route('/client/modif/profile', methods=['GET'])
def client_profile():
    mycursor = get_db().cursor()
    sql = '''
    SELECT * FROM Utilisateur WHERE idUser = %s;
    '''
    mycursor.execute(sql, session['user_id'])
    user = mycursor.fetchone()

    sql = '''
        SELECT * FROM Adresse WHERE idUser = %s;
        '''
    mycursor.execute(sql, session['user_id'])
    adresse = mycursor.fetchall()
    print(adresse)

    return render_template('client/Profile/profil.html', user=user, adresse=adresse)


@client_modif.route('/client/modif/add_Adresse')
def link_add_Adresse():
    return render_template('client/Profile/adresseAdd.html')


@client_modif.route('/client/modif/valid_add_adresse', methods=['POST'])
def add_Adresse():
    mycursor = get_db().cursor()
    adresse = request.form.get('adresse', '')
    code_postale = request.form.get('code_postale', '')
    ville = request.form.get('ville', '')
    tuple_add = (adresse, code_postale, ville, session['user_id'])
    sql = '''
    INSERT INTO Adresse VALUE (NULL, %s, %s, %s, %s);
    '''
    mycursor.execute(sql, tuple_add)
    get_db().commit()
    print(tuple_add)

    return redirect(url_for('client_modif.client_profile'))


@client_modif.route('/client/modif/editAdresse/<int:idAdresse>')
def edit_adresse(idAdresse):
    mycursor = get_db().cursor()
    sql = '''SELECT * FROM Adresse WHERE idAdresse=%s'''
    mycursor.execute(sql, idAdresse)
    Adresse = mycursor.fetchone()
    print(Adresse)
    return render_template('client/Profile/editAdresse.html', Adresse=Adresse)


@client_modif.route('/client/modif/valid_edit_Adresse/', methods=['POST'])
def valid_edit_adresse():
    mycursor = get_db().cursor()
    idAdresse = request.form.get('id', '')
    adresse = request.form.get('adresse', '')
    code_postale = request.form.get('code_postale', '')
    ville = request.form.get('ville', '')
    tuple_edit=(adresse, code_postale, ville, idAdresse)
    sql = '''
    UPDATE Adresse
    SET adresse=%s, code_postale=%s, ville=%s
    WHERE idAdresse=%s
    '''
    mycursor.execute(sql, tuple_edit)
    get_db().commit()
    return redirect(url_for('client_modif.client_profile'))


@client_modif.route('/client/modif/deleteAdresse/<int:idAdresse>', methods=['GET'])
def delete_Adresse(idAdresse):
    mycursor = get_db().cursor()

    # ---------------------------

    sql = '''SELECT * FROM Commande 
                 WHERE idAdresse = %s'''
    mycursor.execute(sql, (idAdresse))
    test_commande = mycursor.fetchall()
    for test in test_commande:
        print(test)
        if ((test.get("idEtat") != 3)):
            message = ("L'adresse avec pour id :" + str(idAdresse)
                       + " ne peut pas etre supprimé car elle est actuellement utiliser dans une commande en cours")
            flash(message)
            return redirect(url_for('client_modif.client_profile'))
        else:
            sql = '''DELETE FROM concerne WHERE idCommande = %s'''
            mycursor.execute(sql, (test["idCommande"]))
            get_db().commit()
            sql = '''DELETE FROM Commande WHERE idAdresse = %s AND idCommande = %s'''
            mycursor.execute(sql, (idAdresse, test["idCommande"]))
            get_db().commit()

    # ---------------------------

    sql = '''DELETE FROM Adresse WHERE idAdresse=%s'''
    mycursor.execute(sql, idAdresse)
    get_db().commit()
    print('Adresse suprimer: ', str(idAdresse))
    message = ("une adresse supprimé, id :" + str(idAdresse))
    flash(message)

    return redirect(url_for('client_modif.client_profile'))

Pycharm/templates/client/Profile/adresseAdd.html
{% extends "client/layout_client.html" %}
{% block body %}
<div class="container">

    <form action="{{ url_for('client_modif.add_Adresse') }}"  method="post">
            <fieldset>
                <legend><h2>Ajout d'une adresse</h2></legend>
                <input type="hidden" name="id">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>
                            <label for="adresse">Adresse</label>
                        </th>
                        <th>
                            <input class="form-control" type="text" placeholder="Entrer votre adresse" name="adresse" required id="adresse">
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <label for="code_postale">Code postale</label>
                        </td>
                        <td>
                            <input class="form-control" type="number" name="code_postale" placeholder="Code postale" required id="code_postale">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="ville">Ville</label>
                        </td>
                        <td>
                            <input class="form-control" type="text" name="ville" placeholder="Ville" required id="ville">
                        </td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <div class="center">
                    <input class="form-control" type="submit" name="f1_submit" value="Valider">
                </div>
            </fieldset>
        </form>



</div>
{% endblock %}

Pycharm/templates/client/Profile/editAdresse.html
{% extends "client/layout_client.html" %}
{% block body %}
<div class="container">

    <form action="{{ url_for('client_modif.valid_edit_adresse') }}"  method="post">
            <fieldset>
                <legend><h2>Edition d'une adresse</h2></legend>
                <input type="hidden" name="id" value="{{ Adresse.idAdresse }}">
                <table class="table">
                    <tbody>
                    <tr>
                        <th>
                            <label for="adresse">Adresse</label>
                        </th>
                        <th>
                            <input class="form-control" type="text" value="{{ Adresse.adresse }}" name="adresse" required id="adresse">
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <label for="code_postale">Code postale</label>
                        </td>
                        <td>
                            <input class="form-control" type="number" name="code_postale" value="{{ Adresse.code_postale }}" required id="code_postale">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label for="ville">Ville</label>
                        </td>
                        <td>
                            <input class="form-control" type="text" name="ville" value="{{ Adresse.ville }}" required id="ville">
                        </td>
                    </tr>
                    </tbody>
                </table>
                <br>
                <div class="center">
                    <input class="form-control" type="submit" name="f1_submit" value="Valider">
                </div>
            </fieldset>
        </form>

</div>
{% endblock %}

Pycharm/templates/client/Profile/profil.html
{% extends "client/layout_client.html" %}
{% block body %}
<div class="container">
    <h3>Mon Profil</h3>
    <h5>
        Mon numéros client: {{ user.idUser }}<br>
        Mon Nom d'utilisateur: {{ user.username }}<br>
        Mon mail: {{ user.email }}<br>
    </h5>

    <h3>Mes adresse</h3>

    <a href="/client/modif/add_Adresse">
        <button class="btn btn-primary float-left">
            Ajouter
        </button>
    </a>
<br>
<br>
<br>

     <table class="table my-0" id="dataTable" style="text-align: center">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>adresse</th>
                            <th>code_postale</th>
                            <th>ville</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% if adresse is defined %}
                            {% for ligne in adresse %}
                                <tr id="" style=" font-weight: bold;">
                                    <td>{{ ligne.idAdresse }}</td>
                                    <td>{{ ligne.adresse}}</td>
                                    <td>{{ ligne.code_postale}}</td>
                                    <td>{{ ligne.ville }} </td>
                                    <td style="text-align: center;">
                                        <a href="/client/modif/editAdresse/{{ ligne.idAdresse }}">
                                            <button class="btn btn-primary float-right ml-2">
                                                Editer
                                             </button>
                                        </a>
                                        <a href="/client/modif/deleteAdresse/{{ ligne.idAdresse }}"  onclick="return confirm('Are you sure?')">
                                            <button class="btn btn-danger float-right">
                                                Supprimer
                                            </button>
                                        </a>
                                    </td>
                                </tr>
                            {% endfor %}
                        {% else %}
                        <tr id="" style="font-weight: bold;">
                            <td>Pas d'adresse</td>
                        </tr>
                        {% endif %}


                        </tbody>
                    </table>
</div>
{% endblock %}